# Generated by Django 5.0.6 on 2024-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ck', '0002_tweet_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
